export const GET_HOMEPAGE_POSTS = 'GET_HOMEPAGE_POSTS';
export const GET_LOGGED_IN_USER_POSTS = 'GET_LOGGED_IN_USER_POSTS';
export const GET_PROFILE_USER_POSTS = 'GET_PROFILE_USER_POSTS';
export const GET_POST_INFO = 'GET_POST_INFO';
export const RESET_POSTS = 'RESET_POSTS';